### ISSUE TITLE
Android 13 been explored yet?

### ISSUE THREAD

**Issue by KatherineKane** [mirfatif/PermissionManagerX#29]
I came across [this reply](https://android.stackexchange.com/a/246765) from you (Irfan) today, just a couple of days after I'd let my Pixel 6 upgrade to Android 13, and I was slightly gutted. I had this ability on my old LG models and it's been making me crazy that I can't remove audio-break-in permissions when I'm trying to listen to a podcast while playing a game. My phone is under contract and even if it's unlikely I'd brick it by by rooting it, would be financially irresponsible of me to risk it right now. 

But since there's no mention of 13 in the PMX help on your website, and the only Play Store reviews for Termux are suggesting no one could get it to run on a Pixel 6, I thought I'd reach out first and ask if there's been any review on ways to install PMX to Android 13, and whether the ADB/Termux instructions would need to be modded for it in some way.

**Comment by mirfatif** [comment]
Hello,

But since there's no mention of 13 in the PMX help on your website...
>

PMX hasn't been tested on Android 13 so far. But it works on Android
13 as reported
by a user <https://t.me/PermissionManagerX/2884>. If there are any issues,
we'll try to fix them.

...and whether the ADB/Termux instructions would need to be modded for it
> in some way
>

We are going to make some changes to PMX so that it won't need Termux for
ADB connection. It's going to work this way
<https://mirfatif.github.io/WhatsRunning/help/en/#adb-help-11>.

Regards.

**Comment by mirfatif** [comment]
> But since there's no mention of 13 in the PMX help on your website...

PMX hasn't been tested on Android 13 so far. But it works on Android 13 as [reported by a user](https://t.me/PermissionManagerX/3162). If there are any issues, we'll try to fix them.

> ...and whether the ADB/Termux instructions would need to be modded for it in some way

We are going to make some changes to PMX so that it won't need Termux for ADB connection. It's going to work [this way](https://mirfatif.github.io/WhatsRunning/help/en/#adb-help-11).
