### ISSUE TITLE
[android r] Root not working

### ISSUE THREAD

**Issue by Sekkei** [mirfatif/PermissionManagerX#3]
I'm on android 11 Miui 12.2 , I granted PMX all permissions (even internet and app ops) isolated storages and query packages are also set.
I use Magisk 21006 (newest canary) , as for now PMX is the only app failing to detect root

I tried to copy the files in .apk/assets to data/adb/module/PMX (creating a magisk module) as I also use the adb for ndk module
I tried the deamon , it goes a little further but still fails to run

**Comment by mirfatif** [comment]
App targets Android 10 at the moment. I haven't tested it on Android 11. You may want to share logcat (or use Collect Logs in the app - if that works on Android 11 - to save log to file), I'll see if that helps.

**Comment by Sekkei** [comment]
This from the in-app log catcher [PermissionManagerX_11-Nov-20_02-49-06.log](https://github.com/mirfatif/PermissionManagerX/files/5521211/PermissionManagerX_11-Nov-20_02-49-06.log)

I could provide a logcat a later if this doesn't help

**Comment by mirfatif** [comment]
Thanks for the logs. App is able to get root privileges and connect to ADB, but daemon is crashing. The reason is not evident from the log. The same is for second (crash) log.

For the first problem you can try setting different UIDs for `Run Privileged Daemon as` under `Advanced Settings`. Also try unchecking `Root Access` so that daemon is started with ADB.

But it's not very likely to work. Highly customized ROMs like MIUI are not very predictable when playing some out of the way tricks. I'll be able to fix the problem only after testing on Android 11, and may be on MIUI in particular.

**Comment by Sekkei** [comment]
Well now I feel stupid.. I tried setting the daemon to run as root within the app and it work immediately (so system seems not to work) 

Thank you for your time

**Comment by mirfatif** [comment]
App targets Android 11 now.
