### ISSUE TITLE
Frequent failures to connect adb wireless debugging

### ISSUE THREAD

**Issue by protonpony** [mirfatif/PermissionManagerX#39]
Only 1 out of 3 attempts to connect wireless debugging succeeds. I must repeatedly disable, pause, and re-enable wireless debugging before the app finally establishes a connection. I strongly recommend adopting Shizuku to acquire the necessary access which should alleviate this behavior. Aside from that, the app is nearly perfect and clearly superior to any other with similar functionality.

**Comment by mirfatif** [comment]
Sorry. [Shizuku is not an option](https://mirfatif.github.io/PermissionManagerX/help/en/#faq30), for now at least.

If you have multiple apps on device which use ADB, connection problems are expected. On all of our test devices including phones and emulators, it never fails to connect. If you provide us more information, we can try to fix the problem.

1. Android version?
2. App version?
3. Connecting the [old way](https://mirfatif.github.io/PermissionManagerX/help/en/#adb-help-10) (`adb tcpip 5555`) or the [new way](https://mirfatif.github.io/PermissionManagerX/help/en/#adb_help_11) (Android 11+ wireless debugging)?
4. Since you said "wireless debugging", so it seems the latter case. Did you try the old way (just for testing) and it also fails?
5. At what stage does exactly it fail? Do you see any error message?
6. Can you please take log (from `adb shell logcat` or in app: About -> Collect Logs) when the error occurs?

**Comment by protonpony** [comment]
I accept your case for rejecting Shizuku, but it is required by several apps on my device and cannot be removed. However, you confirmed my suspicion that it is likely interfering with PMX since they both access ADB (the new way). It's unfortunate but tolerable. Thank-you for the prompt response and all your hard work.
