### ISSUE TITLE
Support work profile apps

### ISSUE THREAD

**Issue by maniusq** [mirfatif/PermissionManagerX#4]
Hi folks,
PermissionManagerX is great 👍 

Unfortunately apps from work profile aren't displayed. The UIDs look like:
`10123 Firefox` (normal/private profile)
`1110123 Firefox` (work profile)

Is it also possible to control these apps?

**Comment by mirfatif** [comment]
Hi @maniusq,
Please install PMX in secondary profile(s) and it should work. Let me know if there are any issues.
If you are using the Play Store version, Play Store needs to be active in secondary profile(s). Or you may use the free version.

**Comment by maniusq** [comment]
Thanks for your quick answer. Install in work profile works :+1: 

To have root privileges in the working profile, I had to select the "Device Owner Managed" setting in Magisk under "Multiuser Mode". Maybe this could be improved, because in AFWall+ the apps from the work profile are displayed without installing AFWall+ in the work profile.

It definitely works. Thanks! :+1:

**Comment by mirfatif** [comment]
> To have root privileges in the working profile, I had to select the "Device Owner Managed" setting in Magisk under "Multiuser Mode".

Yup that's required. I've mentioned that in Help under FAQs.

> Maybe this could be improved, because in AFWall+ the apps from the work profile are displayed without installing AFWall+ in the work profile.

You are absolutely correct. There are many apps which use the same approach. While having root or ADB access, it's not impossible to get packages installed in secondary profiles. But this requires some extra work since profiles are meant to be isolated and Android doesn't want you do so in a straightforward manner (see [`getInstalledPackages`](https://developer.android.com/reference/android/content/pm/PackageManager#getInstalledPackages(int)) _returns a List of all packages that are installed for the **current user**_). And since fetching only package name and UID isn't enough in out case (PMX is quite verbose about package information), it requires even more work, and may also slow down the package loading process (which is already a grey area in my opinion).

So I'm not considering this at the moment but may be in future. Thanks and do keep suggesting, it helps.

**Comment by maniusq** [comment]
Thank you for your detailed explanation :+1:

Sorry for not reading the FAQs. I think the issue can be closed :blush:
